[build]
  command = "make build"
  base = "."
  functions = "./functions"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/netlify/aws-lambda-go-example"